### ISSUE TITLE
Differences with dependency-check?

### ISSUE THREAD

**Issue by julien-f** [jden/node-sanitycheck#4]

**Comment by junosuarez** [comment]
This uses [depscan](https://www.npmjs.com/package/depscan) (which appears to be similar to [dependency-check](https://www.npmjs.com/package/dependency-check)) to make sure that
- all dependencies required in your code are included in package.json
- all dependencies in package.json are required in your code

additionally, it uses [valiquire](https://www.npmjs.com/package/valiquire) to make sure that
- all required files exist on disk
- all required files use the SamE CASing as the filename on disk (this is useful when working with a mix of case-sensitive and case-insensitive file systems)

Thanks for the question!
